// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Todo struct {
	ID   string `json:"ID"`
	Text string `json:"text"`
	Done bool   `json:"done"`
}

type TodoInput struct {
	Text string `json:"text"`
	Done bool   `json:"done"`
}
