package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"
	"module/graph/common"
	"module/graph/model"

	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, text string, done bool, id string) (*model.Todo, error) {
	// Retrieve the database connection from the context

	// Construct a new todo item with the provided text
	todo := &model.Todo{
		ID:   id,
		Text: text,
		Done: done, // Assuming todos are initially not done
	}
	fmt.Println(todo)

	// Insert the new todo item into the database
	if err := db.Create(todo).Error; err != nil {
		return nil, err
	}

	return todo, nil
}

// UpdateTodo is the resolver for the updateTodo field.
func (r *mutationResolver) UpdateTodo(ctx context.Context, id string, input model.TodoInput) (*model.Todo, error) {
	// context := common.GetContext(ctx)
	todo := &model.Todo{
		ID:   id,
		Text: input.Text,
		Done: input.Done,
	}
	err := db.Save(&todo).Error
	if err != nil {
		return nil, err
	}
	return todo, nil
}

// DeleteTodo is the resolver for the deleteTodo field.
func (r *mutationResolver) DeleteTodo(ctx context.Context, todoID string) (*model.Todo, error) {
	context := common.GetContext(ctx)
	var todo *model.Todo
	err := context.Database.Where("id = ?", todoID).Delete(&todo).Error
	if err != nil {
		return nil, err
	}
	return todo, nil
}

// GetTodos is the resolver for the getTodos field.
func (r *queryResolver) GetTodos(ctx context.Context) ([]*model.Todo, error) {
	var todos []*model.Todo
	err := db.Find(&todos).Error
	if err != nil {
		return nil, err
	}
	return todos, nil

	//     todos := []*model.Todo{
	//     {ID: "1", Text: "Buy groceries", Done: false},
	//     {ID: "2", Text: "Walk the dog", Done: true},
	//     {ID: "3", Text: "complete the svelte", Done: false},
	//     // Add more mock todos as needed

	// }
	// return todos, nil
}

// GetTodo is the resolver for the getTodo field.
func (r *queryResolver) GetTodo(ctx context.Context, todoID string) (*model.Todo, error) {
	context := common.GetContext(ctx)
	var todo *model.Todo
	err := context.Database.Where("id = ?", todoID).Find(&todo).Error
	if err != nil {
		return nil, err
	}
	return todo, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
var db *gorm.DB

func init() {
	db, _ = gorm.Open(sqlite.Open("dev.db"), &gorm.Config{
		Logger: logger.Default.LogMode(logger.Silent),
	})
}
